// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASxYfT1c_fVZOTSbjYU2tp1GwNyBWvP0g',
    appId: '1:1047106688432:web:21af7e260fbebf046f7275',
    messagingSenderId: '1047106688432',
    projectId: 'tenacious-moon-348609',
    authDomain: 'tenacious-moon-348609.firebaseapp.com',
    databaseURL: 'https://tenacious-moon-348609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tenacious-moon-348609.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnrNuxcSaXDdk2Sz0gRM_WV2kUKfSDw8',
    appId: '1:1047106688432:android:0a033aca85b928e96f7275',
    messagingSenderId: '1047106688432',
    projectId: 'tenacious-moon-348609',
    databaseURL: 'https://tenacious-moon-348609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tenacious-moon-348609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPBVua1W75oOVjNWj5NV3n20-OJYOSns',
    appId: '1:1047106688432:ios:ad278705d48417986f7275',
    messagingSenderId: '1047106688432',
    projectId: 'tenacious-moon-348609',
    databaseURL: 'https://tenacious-moon-348609-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tenacious-moon-348609.appspot.com',
    iosClientId: '1047106688432-fdq2brumd8n7rtomesu2e46s4rukrkob.apps.googleusercontent.com',
    iosBundleId: 'com.entenreich.connactivity',
  );
}
